// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEFKy5KZ5XVsEIWnl6xmKZkeiugAOII-k',
    appId: '1:656243499438:web:33b726379d17b5c17a683f',
    messagingSenderId: '656243499438',
    projectId: 'nusacerita',
    authDomain: 'nusacerita.firebaseapp.com',
    storageBucket: 'nusacerita.firebasestorage.app',
    measurementId: 'G-6K3SSQXS2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT4N5kfakcaqq96xSGJ51XF3fov7ltO2o',
    appId: '1:656243499438:android:7f8f2c59a6bb5c8a7a683f',
    messagingSenderId: '656243499438',
    projectId: 'nusacerita',
    storageBucket: 'nusacerita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETZy91Fjw8zwXOIriEm8RECl8Bce19cU',
    appId: '1:656243499438:ios:faf6a7f5bca8ddd27a683f',
    messagingSenderId: '656243499438',
    projectId: 'nusacerita',
    storageBucket: 'nusacerita.firebasestorage.app',
    iosBundleId: 'com.example.nusacerita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAETZy91Fjw8zwXOIriEm8RECl8Bce19cU',
    appId: '1:656243499438:ios:faf6a7f5bca8ddd27a683f',
    messagingSenderId: '656243499438',
    projectId: 'nusacerita',
    storageBucket: 'nusacerita.firebasestorage.app',
    iosBundleId: 'com.example.nusacerita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEFKy5KZ5XVsEIWnl6xmKZkeiugAOII-k',
    appId: '1:656243499438:web:fa717d189148e3707a683f',
    messagingSenderId: '656243499438',
    projectId: 'nusacerita',
    authDomain: 'nusacerita.firebaseapp.com',
    storageBucket: 'nusacerita.firebasestorage.app',
    measurementId: 'G-4WC79C2780',
  );
}